language: emacs-lisp
dist: trusty

install:
  - curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/travis-eldev-and-evm > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use

env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-26.2-travis
  - EVM_EMACS=emacs-26.3-travis

script:
  - eldev -p -dtT test --expect 100
  # Run it once again unpackaged, so that `undercover' can collect coverage statistics.
  - eldev -dtT test --expect 100
  - eldev -dtT compile --warnings-as-errors
